url:                   ""
lang:                  en
title:                 HPC.social
baseurl:               "/noodles-award"

description:           Noodles Award

# Format of the permalinks
permalink:             /news/:categories/:year/:title/

defaults:
  # Don't include documents in assets in the sitemap
  - scope:
      path:            assets/
    values:
      sitemap:         false


kramdown:
  math_engine:         mathjax
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'


plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at


# Used for twitter cards
twitter:
  username:            hpc_social

# Used on index and about sites
social:
  name:                HPC Social
  github:              hpc-social
  mastodon:            https://mast.hpc.social/about
  links:
    - https://twitter.com/hpc_social
    - https://github.com/hpc-social
